/// Flutter icons Bottom_Icons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bottom_Icons
///      fonts:
///       - asset: fonts/Bottom_Icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bottom_Icons {
  Bottom_Icons._();

  static const _kFontFam = 'Bottom_Icons';
  static const _kFontPkg = null;

  static const IconData base_icons_promotion = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData base_icons_shop = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData base_icons_home = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData base_icons_news = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
